### ISSUE TITLE
Example of WMTS ?

### ISSUE THREAD

**Issue by btranggg** [slutske22/react-esri-leaflet#21]
Sorry if this question makes no sense. I was wondering if there is an example of this package rendering WMTS data? I tried searching around but couldn't find any concrete examples.

**Comment by slutske22** [comment]
As far as I can see, there is nothing within [esri-leaflet specific to WMS or WMTS layers](https://developers.arcgis.com/esri-leaflet/api-reference/).  Since this library is just a react wrapper for esri-leaflet, there's nothing here for that either.

react-leaflet already supports [WMS Tile Layers](https://react-leaflet.js.org/docs/api-components/#wmstilelayer), as does [native leaflet](https://leafletjs.com/examples/wms/wms.html).  I recommend you try using the WMSTileLayer from react-leaflet, with your esri WMTS endpoint - should work just fine.

Closing as this is not an issue with this library.
